In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle
from joblib import Parallel, delayed
from tqdm import tqdm
from itertools import product
from itertools import permutations
from itertools import combinations
from pyEDM import *
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import Ridge
from sklearn.ensemble import HistGradientBoostingRegressor
import time
import os
import math
import random
from scipy.stats import ttest_ind
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

from IPython.display import display, HTML
display(HTML('<style>.container { width:90% !important; }</style>'))

import warnings
warnings.filterwarnings("ignore", 
    message="A worker stopped while some jobs were given to the executor.",
    module="joblib.externals.loky.process_executor")

In [3]:
def get_block(data, num_lags=1, tau=1):
    ''' Get a dataframe with all the possible valid lags of the variables. '''
    
    block = pd.concat([data[var].shift(lag*tau).rename(f'{var}(t-{lag*tau})') for lag in range(num_lags+1) for var in data.columns], axis=1)

    return block

In [4]:
def ccm(interaction, block, E_list, tau_list, theta_list, Tp, sample=50, sig=0.05):
    #solver = HistGradientBoostingRegressor() #TRYING DIFFERNT SOLVER TO ENSURE CONVERGENCE



    print(interaction)
    lib = f'1 {len(block)}'
    
    # Get dataframe with two species of interest
    A = interaction[0]; B = interaction[1]
    df = block[[f'{A}(t-0)', f'{B}(t-0)']]
    
    driver = f'{A}(t-0)'    
    default_output = {
        'target (driver)': A,
        'lib (driven)': B,
        'E': None,
        'tau': None,
        'theta': None,
        'E_tau_theta_results': None,
        'ccm_value': None,
        'convergence_p_value': None,
        'correlation': None
    }
    
    E_tau_theta_results = pd.DataFrame(columns = ['E', 'tau', 'theta', 'rho'])
    for E, tau, theta in list(product(E_list, tau_list, theta_list)):
        driven_embedded = [f'{B}(t{i})' if i < 0 else f'{B}(t-{i})' for i in range(E * tau, 1)]
        driven_embedded = driven_embedded[::tau][:E]
        try:
            c = SMap(dataFrame=block, target=driver, columns=driven_embedded, embedded=True, Tp=Tp, theta=theta, lib=lib, pred=lib, noTime=True)
        except:
            print(f"{interaction} did not converge")
            return default_output
        c = c['predictions'][['Observations', 'Predictions']]
        rho = c.corr().iloc[0,1]
        E_tau_theta_results.loc[len(E_tau_theta_results)] = [E, tau, theta, rho]
    E_tau_theta_results = E_tau_theta_results.apply(pd.to_numeric, errors='coerce')

    # Assign E, tau, and theta to be the optimal E, tau, and theta
    ccm_value = E_tau_theta_results['rho'].max()
    E = int(E_tau_theta_results.loc[np.where(E_tau_theta_results.rho==ccm_value),'E'].item())
    tau = int(E_tau_theta_results.loc[np.where(E_tau_theta_results.rho==ccm_value),'tau'].item())
    theta = int(E_tau_theta_results.loc[np.where(E_tau_theta_results.rho==ccm_value),'theta'].item())
        
    # Get convergence p-value
    try:
        convergence_p_value = get_convergence_p_value(block, sample, A, B, E, Tp, tau, theta)
    except:
        print(f"{interaction} did not converge")
        return default_output

    # Preparing Output
    output = {
        'target (driver)': A,
        'lib (driven)': B,
        'E': E,
        'tau': tau,
        'theta': theta,
        'E_tau_theta_results': E_tau_theta_results,
        'ccm_value': ccm_value,
        'convergence_p_value': convergence_p_value,
        'correlation': df.corr().iloc[0,1]
    }

    return output

def get_convergence_p_value(df, sample, A, B, E, Tp, tau, theta):
    # Get convergence p-value for CCM (one-tailed t-test on cross-map values using 20% and 50% library sizes)
    # H0: μ_20% ≥ μ_50%
    # HA: μ_20% < μ_50%
    # If p < 0.05, the 20% library size trials have a rho that is significantly smaller than the 50% library trials  
    
    libsize1 = int(np.ceil(df.shape[0]/5))   # 20% of the full library size
    libsize2 = int(np.ceil(df.shape[0]/2))   # 50% of the full library size
    
    max_iterations = 10 * sample
    
    # Get list of rhos for libsize1
    rhos1 = []; iteration_count = 0
    while len(rhos1) < sample and iteration_count < max_iterations:
        start = np.random.randint(libsize1, len(df))
        library = [start - libsize1, start]
        data_subset = df.iloc[library[0]:library[1]]
        lib = f'{library[0]+1} {library[1]+1}'
        driver = f'{A}(t-0)'
        driven_embedded = [f'{B}(t{i})' if i < 0 else f'{B}(t-{i})' for i in range(E * tau, 1)]
        driven_embedded = driven_embedded[::tau][:E]
        c = SMap(dataFrame=block, target=driver, columns=driven_embedded, embedded=True, Tp=Tp, theta=theta, lib=lib, pred=lib, noTime=True)
        c = c['predictions'][['Observations', 'Predictions']]
        rho1 = c.corr().iloc[0,1]
        if not np.isnan(rho1):
            rhos1.append(rho1)
        iteration_count += 1
        
    # Get list of rhos for libsize2
    rhos2 = []; iteration_count = 0
    while len(rhos2) < sample and iteration_count < max_iterations:
        start = np.random.randint(libsize2, len(df))
        library = [start - libsize2, start]
        data_subset = df.iloc[library[0]:library[1]]
        lib = f'{library[0]+1} {library[1]+1}'
        driver = f'{A}(t-0)'
        driven_embedded = [f'{B}(t{i})' if i < 0 else f'{B}(t-{i})' for i in range(E * tau, 1)]
        driven_embedded = driven_embedded[::tau][:E]
        c = SMap(dataFrame=block, target=driver, columns=driven_embedded, embedded=True, Tp=Tp, theta=theta, lib=lib, pred=lib, noTime=True)
        c = c['predictions'][['Observations', 'Predictions']]
        rho2 = c.corr().iloc[0,1]
        if not np.isnan(rho2):
            rhos2.append(rho2)
        iteration_count += 1
    
    convergence_t_stat, convergence_p_value = ttest_ind(rhos1, rhos2, alternative='less')
    
    return convergence_p_value

In [45]:
HAB_data = pd.read_csv('Data/carter_data_w_gaps.csv', index_col=0) #LOAD DATA

In [46]:
HAB_data

,Matlab Date,Time Collected PT (hhmm),Temp (deg C),Chl Volume Filtered (mL),Chl1 (mg/m3),Chl2 (mg/m3),Avg Chloro (mg/m3),Phaeo1 (mg/m3),Phaeo2 (mg/m3),Avg Phaeo (mg/m3),...,'Lingulodinium_polyedra',Total_Prorocentrum_spp','Total_Dinoflagellates','Total_Phytoplankton',DATE,SURF_SAL_PSU,BOT_SAL_PSU,SURF_TEMP_C,BOT_TEMP_C,WSPD
0,733589.333333,800,19.8,100.0,1.81,1.83,1.82,0.59,0.61,0.60,...,89.0,5168.0,15684.0,85636.0,2008-06-30,33.77,33.62,20.3,15.9,4.691667
1,733591.326389,750,19.7,100.0,2.04,2.12,2.08,0.53,0.52,0.53,...,NaN,NaN,NaN,NaN,2008-07-02,33.74,33.60,19.9,16.5,3.954167
2,733596.333333,800,17.3,100.0,2.68,2.73,2.71,1.24,1.12,1.18,...,89.0,1158.0,5703.0,173233.0,2008-07-07,33.66,33.62,17.8,16.9,2.787500
3,733599.361111,840,19.5,100.0,1.30,1.34,1.32,0.51,0.53,0.52,...,NaN,NaN,NaN,NaN,2008-07-10,33.44,33.53,19.8,19.6,2.825000
4,733603.329167,755,21.7,100.0,0.99,1.00,0.99,0.55,0.54,0.55,...,267.0,1069.0,10515.0,77616.0,2008-07-14,33.74,33.58,22.2,18.3,3.412500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1597,739602.451389,1051,13.8,100.0,3.51,3.25,3.38,0.88,1.13,1.00,...,0.0,1252.0,63206.0,158328.0,2024-12-16,33.38,33.36,13.5,13.4,5.088889
1598,739605.493750,1152,14.2,100.0,6.93,6.57,6.75,0.86,0.89,0.88,...,NaN,NaN,NaN,NaN,2024-12-19,33.37,33.35,14.3,14.0,2.736806
1599,739609.517361,1226,13.2,100.0,9.86,9.57,9.71,1.51,1.47,1.49,...,10013.0,22529.0,165212.0,452455.0,2024-12-23,33.36,NaN,13.3,NaN,2.813194
1600,739612.509028,1213,13.3,100.0,20.74,19.16,19.95,3.32,2.87,3.10,...,NaN,NaN,NaN,NaN,2024-12-26,33.40,33.37,13.1,13.2,5.293056
1601,739616.514583,1221,13.4,100.0,5.71,5.37,5.54,1.43,1.43,1.43,...,4381.0,61954.0,153321.0,252823.0,2024-12-30,33.39,33.38,13.7,13.5,3.964583

In [41]:
HAB_data.columns

Index(['AVG_DENS_kgm3', 'AVG_SAL_PSU', 'AVG_TEMP_C', 'Avg_Chloro',
       'BOT_DENS_kgm3', 'BOT_SAL_PSU', 'BOT_TEMP_C', 'Nitrate', 'Nitrite',
       'Phosphate', 'SURF_DENS_kgm3', 'SURF_SAL_PSU', 'SURF_TEMP_C',
       'Silicate', 'WSPD'],
      dtype='object')

In [60]:
# HAB_data = pd.read_csv('Data/data_w_gaps_and_wind.csv', index_col=0)#.iloc[304:612] RANGE w/o missing values
HAB_data = HAB_data.reset_index()
HAB_data.columns = HAB_data.columns.str.replace(' ', '_')

# Put columns in alphabetical order
sorted_columns = sorted(HAB_data.columns)
HAB_data = HAB_data[sorted_columns]
HAB_data = HAB_data.set_index('time')

target = 'Avg_Chloro' #change target if needed

# Make indices integers and save mapping to dates
#date_to_int_map = {i: date for i, date in enumerate(HAB_data.index)}
#HAB_data.index = range(len(HAB_data))

HAB_data.columns

KeyError: "None of ['time'] are in the columns"

In [33]:
print(HAB_data.isna().sum())

AVG_DENS_kgm3     98
AVG_SAL_PSU       95
AVG_TEMP_C        96
Avg_Chloro        10
BOT_DENS_kgm3     95
BOT_SAL_PSU       92
BOT_TEMP_C        95
Nitrate            0
Nitrite            0
Phosphate          0
SURF_DENS_kgm3    53
SURF_SAL_PSU      51
SURF_TEMP_C       51
Silicate           0
WSPD              32
dtype: int64

In [34]:
#IMPUTE HAB DATA
#Build basic linear regression model as sanity check
# Custom impute missing values with the average of the value in front and behind of it 
class ForwardBackwardImputer(BaseEstimator, TransformerMixin):
    def __init__(self):
        pass

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X_filled_forward = X.fillna(method='ffill').fillna(method='bfill')
        X_filled_backward = X.fillna(method='bfill').fillna(method='ffill')

        return (X_filled_forward + X_filled_backward) / 2


Imputer = ForwardBackwardImputer()
HAB_data = HAB_data.apply(pd.to_numeric, errors='coerce')
Imputer.fit(HAB_data)
HAB_data = Imputer.transform(HAB_data)#COMMENT OUT IF DONT WANT MEAN MPUTE
HAB_data

/var/folders/1_/l6tr0bbn3mb7vblmfq8qmf_40000gn/T/ipykernel_48149/137097351.py:12: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  X_filled_forward = X.fillna(method='ffill').fillna(method='bfill')
/var/folders/1_/l6tr0bbn3mb7vblmfq8qmf_40000gn/T/ipykernel_48149/137097351.py:13: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  X_filled_backward = X.fillna(method='bfill').fillna(method='ffill')

,AVG_DENS_kgm3,AVG_SAL_PSU,AVG_TEMP_C,Avg_Chloro,BOT_DENS_kgm3,BOT_SAL_PSU,BOT_TEMP_C,Nitrate,Nitrite,Phosphate,SURF_DENS_kgm3,SURF_SAL_PSU,SURF_TEMP_C,Silicate,WSPD
time,,,,,,,,,,,,,,,
0,1024.129374,33.695,18.10,1.82,1024.620655,33.62,15.9,0.43,0.03,0.24,1023.638094,33.77,20.3,5.6,4.691667
7,1024.289049,33.640,17.35,2.71,1024.391719,33.62,16.9,0.83,0.04,0.37,1024.186379,33.66,17.8,5.1,2.787500
13,1023.563298,33.660,20.25,0.99,1024.026040,33.58,18.3,0.45,0.00,0.24,1023.100557,33.74,22.2,3.5,3.412500
20,1023.740812,33.650,9.90,1.23,1023.780535,33.62,19.4,0.34,0.00,0.17,1023.701088,33.68,19.8,4.2,3.495833
28,1023.004896,33.710,11.25,2.41,1023.000725,33.69,22.5,0.29,0.00,0.12,1023.009067,33.73,22.5,3.8,2.604167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5789,1024.149572,33.470,17.40,3.22,1024.152950,33.46,17.4,0.85,0.00,0.30,1024.146195,33.48,17.4,6.2,5.076389
5796,1024.033476,33.475,17.90,3.39,1024.040616,33.47,17.9,0.45,0.00,0.25,1024.026335,33.48,17.9,4.9,2.737500
5803,1024.214172,33.545,17.35,7.82,1024.454252,33.55,16.4,0.00,0.00,0.17,1023.974093,33.54,18.3,5.2,3.306250
5811,1024.194573,33.625,17.70,17.30,1024.266323,33.61,17.4,0.00,0.00,0.20,1024.122823,33.64,18.0,9.4,2.418056
5817,1024.169303,33.625,17.80,16.71,1024.321284,33.62,17.2,0.00,0.00,0.10,1024.017322,33.63,18.4,7.5,2.568056

In [35]:
print(HAB_data.isna().sum())

AVG_DENS_kgm3     0
AVG_SAL_PSU       0
AVG_TEMP_C        0
Avg_Chloro        0
BOT_DENS_kgm3     0
BOT_SAL_PSU       0
BOT_TEMP_C        0
Nitrate           0
Nitrite           0
Phosphate         0
SURF_DENS_kgm3    0
SURF_SAL_PSU      0
SURF_TEMP_C       0
Silicate          0
WSPD              0
dtype: int64

In [36]:
#STANDARDIZE
#LEFT OFF HERE THERE IS AN ERROR
'''
scaler = MinMaxScaler()
columns = ['AVG_DENS_kgm3', 'AVG_SAL_PSU', 'AVG_TEMP_C', 'Avg_Chloro', 
           'BOT_DENS_kgm3', 'BOT_SAL_PSU', 'BOT_TEMP_C', 'Nitrate', 'Nitrite', 
           'Phosphate', 'SURF_DENS_kgm3', 'SURF_SAL_PSU', 'SURF_TEMP_C', 
           'Silicate', 'WSPD']
HAB_data[columns] = scaler.fit_transform(HAB_data[columns])
HAB_data
'''

"\nscaler = MinMaxScaler()\ncolumns = ['AVG_DENS_kgm3', 'AVG_SAL_PSU', 'AVG_TEMP_C', 'Avg_Chloro', \n           'BOT_DENS_kgm3', 'BOT_SAL_PSU', 'BOT_TEMP_C', 'Nitrate', 'Nitrite', \n           'Phosphate', 'SURF_DENS_kgm3', 'SURF_SAL_PSU', 'SURF_TEMP_C', \n           'Silicate', 'WSPD']\nHAB_data[columns] = scaler.fit_transform(HAB_data[columns])\nHAB_data\n"

In [37]:
HAB_data.drop(columns=[]) # FOR MELISSA CARTER DATA
block = get_block(HAB_data, num_lags=50, tau=1)
block

,AVG_DENS_kgm3(t-0),AVG_SAL_PSU(t-0),AVG_TEMP_C(t-0),Avg_Chloro(t-0),BOT_DENS_kgm3(t-0),BOT_SAL_PSU(t-0),BOT_TEMP_C(t-0),Nitrate(t-0),Nitrite(t-0),Phosphate(t-0),...,BOT_SAL_PSU(t-50),BOT_TEMP_C(t-50),Nitrate(t-50),Nitrite(t-50),Phosphate(t-50),SURF_DENS_kgm3(t-50),SURF_SAL_PSU(t-50),SURF_TEMP_C(t-50),Silicate(t-50),WSPD(t-50)
time,,,,,,,,,,,,,,,,,,,,,
0,1024.129374,33.695,18.10,1.82,1024.620655,33.62,15.9,0.43,0.03,0.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1024.289049,33.640,17.35,2.71,1024.391719,33.62,16.9,0.83,0.04,0.37,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1023.563298,33.660,20.25,0.99,1024.026040,33.58,18.3,0.45,0.00,0.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1023.740812,33.650,9.90,1.23,1023.780535,33.62,19.4,0.34,0.00,0.17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1023.004896,33.710,11.25,2.41,1023.000725,33.69,22.5,0.29,0.00,0.12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5789,1024.149572,33.470,17.40,3.22,1024.152950,33.46,17.4,0.85,0.00,0.30,...,33.56,17.4,0.24,0.0,0.94,1024.206663,33.56,17.4,5.8,1.879861
5796,1024.033476,33.475,17.90,3.39,1024.040616,33.47,17.9,0.45,0.00,0.25,...,33.52,17.9,0.31,0.0,0.92,1024.056525,33.52,17.9,1.9,3.991667
5803,1024.214172,33.545,17.35,7.82,1024.454252,33.55,16.4,0.00,0.00,0.17,...,33.43,13.8,0.58,0.0,0.99,1024.177462,33.49,17.3,2.9,3.043056
5811,1024.194573,33.625,17.70,17.30,1024.266323,33.61,17.4,0.00,0.00,0.20,...,33.46,17.3,0.72,0.0,0.96,1024.178392,33.46,17.2,3.8,3.334722
5817,1024.169303,33.625,17.80,16.71,1024.321284,33.62,17.2,0.00,0.00,0.10,...,33.44,17.2,0.33,0.0,0.82,1023.955145,33.45,18.1,2.0,2.472222

In [38]:
E_list = range(2,13)
tau_list = [-1,-2,-3] #can try more taus
theta_list = [0,0.1,0.5,1,2,3,4,5,6,7,8,9]
Tp = 0
exclusion_radius = 0

all_ccm_results = pd.DataFrame()
interactions = list(permutations(HAB_data.columns.tolist(),2))
print(interactions)
target_interactions = [pair for pair in interactions if target in pair]

interaction = target_interactions[0]
print(f'There are {len(target_interactions)} interactions')

results = Parallel(n_jobs=4)(
    delayed(ccm)(interaction, block, E_list, tau_list, theta_list, Tp) for interaction in target_interactions)
results_df = pd.DataFrame(results)

[('AVG_DENS_kgm3', 'AVG_SAL_PSU'), ('AVG_DENS_kgm3', 'AVG_TEMP_C'), ('AVG_DENS_kgm3', 'Avg_Chloro'), ('AVG_DENS_kgm3', 'BOT_DENS_kgm3'), ('AVG_DENS_kgm3', 'BOT_SAL_PSU'), ('AVG_DENS_kgm3', 'BOT_TEMP_C'), ('AVG_DENS_kgm3', 'Nitrate'), ('AVG_DENS_kgm3', 'Nitrite'), ('AVG_DENS_kgm3', 'Phosphate'), ('AVG_DENS_kgm3', 'SURF_DENS_kgm3'), ('AVG_DENS_kgm3', 'SURF_SAL_PSU'), ('AVG_DENS_kgm3', 'SURF_TEMP_C'), ('AVG_DENS_kgm3', 'Silicate'), ('AVG_DENS_kgm3', 'WSPD'), ('AVG_SAL_PSU', 'AVG_DENS_kgm3'), ('AVG_SAL_PSU', 'AVG_TEMP_C'), ('AVG_SAL_PSU', 'Avg_Chloro'), ('AVG_SAL_PSU', 'BOT_DENS_kgm3'), ('AVG_SAL_PSU', 'BOT_SAL_PSU'), ('AVG_SAL_PSU', 'BOT_TEMP_C'), ('AVG_SAL_PSU', 'Nitrate'), ('AVG_SAL_PSU', 'Nitrite'), ('AVG_SAL_PSU', 'Phosphate'), ('AVG_SAL_PSU', 'SURF_DENS_kgm3'), ('AVG_SAL_PSU', 'SURF_SAL_PSU'), ('AVG_SAL_PSU', 'SURF_TEMP_C'), ('AVG_SAL_PSU', 'Silicate'), ('AVG_SAL_PSU', 'WSPD'), ('AVG_TEMP_C', 'AVG_DENS_kgm3'), ('AVG_TEMP_C', 'AVG_SAL_PSU'), ('AVG_TEMP_C', 'Avg_Chloro'), ('AVG_TEMP_C', 'BOT_DENS_kgm3'), ('AVG_TEMP_C', 'BOT_SAL_PSU'), ('AVG_TEMP_C', 'BOT_TEMP_C'), ('AVG_TEMP_C', 'Nitrate'), ('AVG_TEMP_C', 'Nitrite'), ('AVG_TEMP_C', 'Phosphate'), ('AVG_TEMP_C', 'SURF_DENS_kgm3'), ('AVG_TEMP_C', 'SURF_SAL_PSU'), ('AVG_TEMP_C', 'SURF_TEMP_C'), ('AVG_TEMP_C', 'Silicate'), ('AVG_TEMP_C', 'WSPD'), ('Avg_Chloro', 'AVG_DENS_kgm3'), ('Avg_Chloro', 'AVG_SAL_PSU'), ('Avg_Chloro', 'AVG_TEMP_C'), ('Avg_Chloro', 'BOT_DENS_kgm3'), ('Avg_Chloro', 'BOT_SAL_PSU'), ('Avg_Chloro', 'BOT_TEMP_C'), ('Avg_Chloro', 'Nitrate'), ('Avg_Chloro', 'Nitrite'), ('Avg_Chloro', 'Phosphate'), ('Avg_Chloro', 'SURF_DENS_kgm3'), ('Avg_Chloro', 'SURF_SAL_PSU'), ('Avg_Chloro', 'SURF_TEMP_C'), ('Avg_Chloro', 'Silicate'), ('Avg_Chloro', 'WSPD'), ('BOT_DENS_kgm3', 'AVG_DENS_kgm3'), ('BOT_DENS_kgm3', 'AVG_SAL_PSU'), ('BOT_DENS_kgm3', 'AVG_TEMP_C'), ('BOT_DENS_kgm3', 'Avg_Chloro'), ('BOT_DENS_kgm3', 'BOT_SAL_PSU'), ('BOT_DENS_kgm3', 'BOT_TEMP_C'), ('BOT_DENS_kgm3', 'Nitrate'), ('BOT_DENS_kgm3', 'Nitrite'), ('BOT_DENS_kgm3', 'Phosphate'), ('BOT_DENS_kgm3', 'SURF_DENS_kgm3'), ('BOT_DENS_kgm3', 'SURF_SAL_PSU'), ('BOT_DENS_kgm3', 'SURF_TEMP_C'), ('BOT_DENS_kgm3', 'Silicate'), ('BOT_DENS_kgm3', 'WSPD'), ('BOT_SAL_PSU', 'AVG_DENS_kgm3'), ('BOT_SAL_PSU', 'AVG_SAL_PSU'), ('BOT_SAL_PSU', 'AVG_TEMP_C'), ('BOT_SAL_PSU', 'Avg_Chloro'), ('BOT_SAL_PSU', 'BOT_DENS_kgm3'), ('BOT_SAL_PSU', 'BOT_TEMP_C'), ('BOT_SAL_PSU', 'Nitrate'), ('BOT_SAL_PSU', 'Nitrite'), ('BOT_SAL_PSU', 'Phosphate'), ('BOT_SAL_PSU', 'SURF_DENS_kgm3'), ('BOT_SAL_PSU', 'SURF_SAL_PSU'), ('BOT_SAL_PSU', 'SURF_TEMP_C'), ('BOT_SAL_PSU', 'Silicate'), ('BOT_SAL_PSU', 'WSPD'), ('BOT_TEMP_C', 'AVG_DENS_kgm3'), ('BOT_TEMP_C', 'AVG_SAL_PSU'), ('BOT_TEMP_C', 'AVG_TEMP_C'), ('BOT_TEMP_C', 'Avg_Chloro'), ('BOT_TEMP_C', 'BOT_DENS_kgm3'), ('BOT_TEMP_C', 'BOT_SAL_PSU'), ('BOT_TEMP_C', 'Nitrate'), ('BOT_TEMP_C', 'Nitrite'), ('BOT_TEMP_C', 'Phosphate'), ('BOT_TEMP_C', 'SURF_DENS_kgm3'), ('BOT_TEMP_C', 'SURF_SAL_PSU'), ('BOT_TEMP_C', 'SURF_TEMP_C'), ('BOT_TEMP_C', 'Silicate'), ('BOT_TEMP_C', 'WSPD'), ('Nitrate', 'AVG_DENS_kgm3'), ('Nitrate', 'AVG_SAL_PSU'), ('Nitrate', 'AVG_TEMP_C'), ('Nitrate', 'Avg_Chloro'), ('Nitrate', 'BOT_DENS_kgm3'), ('Nitrate', 'BOT_SAL_PSU'), ('Nitrate', 'BOT_TEMP_C'), ('Nitrate', 'Nitrite'), ('Nitrate', 'Phosphate'), ('Nitrate', 'SURF_DENS_kgm3'), ('Nitrate', 'SURF_SAL_PSU'), ('Nitrate', 'SURF_TEMP_C'), ('Nitrate', 'Silicate'), ('Nitrate', 'WSPD'), ('Nitrite', 'AVG_DENS_kgm3'), ('Nitrite', 'AVG_SAL_PSU'), ('Nitrite', 'AVG_TEMP_C'), ('Nitrite', 'Avg_Chloro'), ('Nitrite', 'BOT_DENS_kgm3'), ('Nitrite', 'BOT_SAL_PSU'), ('Nitrite', 'BOT_TEMP_C'), ('Nitrite', 'Nitrate'), ('Nitrite', 'Phosphate'), ('Nitrite', 'SURF_DENS_kgm3'), ('Nitrite', 'SURF_SAL_PSU'), ('Nitrite', 'SURF_TEMP_C'), ('Nitrite', 'Silicate'), ('Nitrite', 'WSPD'), ('Phosphate', 'AVG_DENS_kgm3'), ('Phosphate', 'AVG_SAL_PSU'), ('Phosphate', 'AVG_TEMP_C'), ('Phosphate', 'Avg_Chloro'), ('Phosphate', 'BOT_DENS_kgm3'), ('Phosphate', 'BOT_SAL_PSU'), ('Phosphate', 'BOT_TEMP_C'), ('Phosphate', 'Nitrate'), ('Phosphate', 'Nitrite'), ('Phosphate', 'SURF_DENS_kgm3'), ('Phosphate', 'SURF_SAL_PSU'), ('Phosphate', 'SURF_TEMP_C'), ('Phosphate', 'Silicate'), ('Phosphate', 'WSPD'), ('SURF_DENS_kgm3', 'AVG_DENS_kgm3'), ('SURF_DENS_kgm3', 'AVG_SAL_PSU'), ('SURF_DENS_kgm3', 'AVG_TEMP_C'), ('SURF_DENS_kgm3', 'Avg_Chloro'), ('SURF_DENS_kgm3', 'BOT_DENS_kgm3'), ('SURF_DENS_kgm3', 'BOT_SAL_PSU'), ('SURF_DENS_kgm3', 'BOT_TEMP_C'), ('SURF_DENS_kgm3', 'Nitrate'), ('SURF_DENS_kgm3', 'Nitrite'), ('SURF_DENS_kgm3', 'Phosphate'), ('SURF_DENS_kgm3', 'SURF_SAL_PSU'), ('SURF_DENS_kgm3', 'SURF_TEMP_C'), ('SURF_DENS_kgm3', 'Silicate'), ('SURF_DENS_kgm3', 'WSPD'), ('SURF_SAL_PSU', 'AVG_DENS_kgm3'), ('SURF_SAL_PSU', 'AVG_SAL_PSU'), ('SURF_SAL_PSU', 'AVG_TEMP_C'), ('SURF_SAL_PSU', 'Avg_Chloro'), ('SURF_SAL_PSU', 'BOT_DENS_kgm3'), ('SURF_SAL_PSU', 'BOT_SAL_PSU'), ('SURF_SAL_PSU', 'BOT_TEMP_C'), ('SURF_SAL_PSU', 'Nitrate'), ('SURF_SAL_PSU', 'Nitrite'), ('SURF_SAL_PSU', 'Phosphate'), ('SURF_SAL_PSU', 'SURF_DENS_kgm3'), ('SURF_SAL_PSU', 'SURF_TEMP_C'), ('SURF_SAL_PSU', 'Silicate'), ('SURF_SAL_PSU', 'WSPD'), ('SURF_TEMP_C', 'AVG_DENS_kgm3'), ('SURF_TEMP_C', 'AVG_SAL_PSU'), ('SURF_TEMP_C', 'AVG_TEMP_C'), ('SURF_TEMP_C', 'Avg_Chloro'), ('SURF_TEMP_C', 'BOT_DENS_kgm3'), ('SURF_TEMP_C', 'BOT_SAL_PSU'), ('SURF_TEMP_C', 'BOT_TEMP_C'), ('SURF_TEMP_C', 'Nitrate'), ('SURF_TEMP_C', 'Nitrite'), ('SURF_TEMP_C', 'Phosphate'), ('SURF_TEMP_C', 'SURF_DENS_kgm3'), ('SURF_TEMP_C', 'SURF_SAL_PSU'), ('SURF_TEMP_C', 'Silicate'), ('SURF_TEMP_C', 'WSPD'), ('Silicate', 'AVG_DENS_kgm3'), ('Silicate', 'AVG_SAL_PSU'), ('Silicate', 'AVG_TEMP_C'), ('Silicate', 'Avg_Chloro'), ('Silicate', 'BOT_DENS_kgm3'), ('Silicate', 'BOT_SAL_PSU'), ('Silicate', 'BOT_TEMP_C'), ('Silicate', 'Nitrate'), ('Silicate', 'Nitrite'), ('Silicate', 'Phosphate'), ('Silicate', 'SURF_DENS_kgm3'), ('Silicate', 'SURF_SAL_PSU'), ('Silicate', 'SURF_TEMP_C'), ('Silicate', 'WSPD'), ('WSPD', 'AVG_DENS_kgm3'), ('WSPD', 'AVG_SAL_PSU'), ('WSPD', 'AVG_TEMP_C'), ('WSPD', 'Avg_Chloro'), ('WSPD', 'BOT_DENS_kgm3'), ('WSPD', 'BOT_SAL_PSU'), ('WSPD', 'BOT_TEMP_C'), ('WSPD', 'Nitrate'), ('WSPD', 'Nitrite'), ('WSPD', 'Phosphate'), ('WSPD', 'SURF_DENS_kgm3'), ('WSPD', 'SURF_SAL_PSU'), ('WSPD', 'SURF_TEMP_C'), ('WSPD', 'Silicate')]
There are 28 interactions

('AVG_SAL_PSU', 'Avg_Chloro')
('Avg_Chloro', 'AVG_DENS_kgm3')
('AVG_DENS_kgm3', 'Avg_Chloro')
('AVG_TEMP_C', 'Avg_Chloro')
('Avg_Chloro', 'AVG_SAL_PSU')
('Avg_Chloro', 'AVG_TEMP_C')
('Avg_Chloro', 'BOT_DENS_kgm3')
('Avg_Chloro', 'BOT_SAL_PSU')
('Avg_Chloro', 'BOT_TEMP_C')
('Avg_Chloro', 'Nitrate')
('Avg_Chloro', 'Nitrite')
('Avg_Chloro', 'Phosphate')

/Users/estherchung/miniforge3/lib/python3.12/site-packages/pyEDM/SMap.py:134: RuntimeWarning: divide by zero encountered in divide
  distRowScale = self.theta / distRowMean
/Users/estherchung/miniforge3/lib/python3.12/site-packages/pyEDM/SMap.py:135: RuntimeWarning: invalid value encountered in multiply
  W = exp( -distRowScale[:,None] * self.knn_distances )

** On entry to DLASCL, parameter number  4 had an illegal value
** On entry to DLASCL, parameter number  4 had an illegal value
('Avg_Chloro', 'Nitrite') did not converge
('Avg_Chloro', 'SURF_DENS_kgm3')
('Avg_Chloro', 'SURF_SAL_PSU')
('Avg_Chloro', 'SURF_TEMP_C')
('Avg_Chloro', 'Silicate')

KeyboardInterrupt:

In [29]:
# Get CCM results that show convergence (convergence p-value < 0.05)
results_df = pd.DataFrame(results)
ccm_cutoff = -1

significant_results = results_df[results_df.convergence_p_value<0.20]
significant_results = significant_results.sort_values(by='ccm_value', ascending=False)
significant_results = significant_results[['target (driver)', 'lib (driven)', 'E', 'tau', 'theta', 'ccm_value']].reset_index(drop=True)

display(significant_results[significant_results.ccm_value>ccm_cutoff])

# Choose system variables where the CCM value to or from the target is > ccm_cutoff
system_variables = significant_results[significant_results.ccm_value > ccm_cutoff]
system_variables = system_variables[['target (driver)', 'lib (driven)']].values.flatten().tolist()
system_variables = list(set(system_variables))
print('system variables: ')
display(sorted(system_variables))

NameError: name 'results' is not defined

In [24]:
results_df[results_df.convergence_p_value<0.8].sort_values(by='convergence_p_value', ascending=False)

NameError: name 'results_df' is not defined

DEYLE DATASET

In [47]:
Orig_block = pd.read_csv('Data/Orig_block.csv')

# Drop the extra lagged columns
# also took out chlA_.1wk --> didn't know what it represented
cols_to_drop = [col for col in Orig_block.columns if '1wk' in col or '_2wk' in col]
Orig_block_clean = Orig_block.drop(columns=cols_to_drop)

In [48]:
Orig_block

,serial_day,chlA_.1wk,chlA,nitrate,phosphate,silicate,nitrite,nitrate_phosphate_ratio,N_star,Si_star,...,nitrate_phosphate_ratio_2wk,N_star_2wk,Si_star_2wk,AvgTemp_1wk_2wk,AvgDens_1wk_2wk,SST_2wk,WIND_SPD_2wk,U_WIND_2wk,PRCP_2wkavg_2wk,AWND_2wkavg_2wk
0,725662,0.920,0.430,2.520,0.295,2.355,0.020,8.542373,-2.200,2.06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,725669,0.615,0.920,2.110,0.305,2.605,0.115,6.918033,-2.770,2.30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,725676,0.655,0.615,1.915,0.370,0.450,0.020,5.175676,-4.005,0.08,...,8.542373,-2.200,2.06,19.125000,1023.8997,19.118428,3.219574,0.398250,25.214286,29.000000
3,725683,0.410,0.655,0.155,0.330,1.500,0.020,0.469697,-5.125,1.17,...,6.918033,-2.770,2.30,18.564286,1024.0495,19.229762,3.243543,0.701107,0.000000,30.428571
4,725690,0.325,0.410,0.200,0.320,2.000,0.030,0.625000,-4.920,1.68,...,5.175676,-4.005,0.08,17.721429,1024.2147,19.083670,2.679270,0.652186,0.000000,29.357143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1836,734926,1.995,1.790,0.940,0.280,4.930,0.120,3.357143,-3.540,4.65,...,2.464286,-3.790,2.40,15.253571,1024.7554,14.476527,3.936310,0.646581,6.000000,19.357143
1837,734933,8.210,1.995,4.360,0.450,7.690,0.270,9.688889,-2.840,7.24,...,5.166667,-3.250,4.29,14.600000,1024.8883,14.179503,4.900595,1.848541,9.428571,25.642857
1838,734940,2.775,8.210,1.490,0.310,4.710,0.110,4.806452,-3.470,4.40,...,3.357143,-3.540,4.65,14.828571,1024.8475,14.007738,4.063095,0.773389,15.428571,26.428571
1839,734947,2.410,2.775,3.760,0.600,6.280,0.230,6.266667,-5.840,5.68,...,9.688889,-2.840,7.24,14.316667,1024.9582,13.920575,4.294345,0.868929,6.928571,24.214286
1840,734954,NaN,2.410,10.520,1.020,11.560,0.310,10.313725,-5.800,10.54,...,4.806452,-3.470,4.40,13.807143,1025.1464,13.516654,4.558411,1.807142,0.214286,24.000000

In [49]:
Orig_block_clean.columns

Index(['serial_day', 'chlA', 'nitrate', 'phosphate', 'silicate', 'nitrite',
       'nitrate_phosphate_ratio', 'N_star', 'Si_star', 'SST', 'WIND_SPD',
       'U_WIND'],
      dtype='object')

In [50]:
Orig_block_clean = Orig_block_clean.reset_index(drop=True)
Orig_block_clean.columns = Orig_block_clean.columns.str.replace(' ', '_')
Orig_block_clean = Orig_block_clean[sorted(Orig_block_clean.columns)]
Orig_block_clean = Orig_block_clean.set_index('serial_day')
target = 'chlA'
Orig_block_clean.columns

Index(['N_star', 'SST', 'Si_star', 'U_WIND', 'WIND_SPD', 'chlA', 'nitrate',
       'nitrate_phosphate_ratio', 'nitrite', 'phosphate', 'silicate'],
      dtype='object')

In [51]:
print(Orig_block_clean.isna().sum())

N_star                     0
SST                        0
Si_star                    0
U_WIND                     0
WIND_SPD                   0
chlA                       0
nitrate                    0
nitrate_phosphate_ratio    0
nitrite                    0
phosphate                  0
silicate                   0
dtype: int64

In [52]:
#IMPUTE HAB DATA
#Build basic linear regression model as sanity check
# Custom impute missing values with the average of the value in front and behind of it 
class ForwardBackwardImputer(BaseEstimator, TransformerMixin):
    def __init__(self):
        pass

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X_filled_forward = X.fillna(method='ffill').fillna(method='bfill')
        X_filled_backward = X.fillna(method='bfill').fillna(method='ffill')

        return (X_filled_forward + X_filled_backward) / 2


Imputer = ForwardBackwardImputer()
Orig_block_clean = Orig_block_clean.apply(pd.to_numeric, errors='coerce')
Imputer.fit(Orig_block_clean)
Orig_block_clean = Imputer.transform(Orig_block_clean)#COMMENT OUT IF DONT WANT MEAN MPUTE
Orig_block_clean

/var/folders/1_/l6tr0bbn3mb7vblmfq8qmf_40000gn/T/ipykernel_48812/2164836750.py:12: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  X_filled_forward = X.fillna(method='ffill').fillna(method='bfill')
/var/folders/1_/l6tr0bbn3mb7vblmfq8qmf_40000gn/T/ipykernel_48812/2164836750.py:13: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  X_filled_backward = X.fillna(method='bfill').fillna(method='ffill')

,N_star,SST,Si_star,U_WIND,WIND_SPD,chlA,nitrate,nitrate_phosphate_ratio,nitrite,phosphate,silicate
serial_day,,,,,,,,,,,
725662,-2.200,19.118428,2.06,0.398250,3.219574,0.430,2.520,8.542373,0.020,0.295,2.355
725669,-2.770,19.229762,2.30,0.701107,3.243543,0.920,2.110,6.918033,0.115,0.305,2.605
725676,-4.005,19.083670,0.08,0.652186,2.679270,0.615,1.915,5.175676,0.020,0.370,0.450
725683,-5.125,18.651255,1.17,0.735618,2.754969,0.655,0.155,0.469697,0.020,0.330,1.500
725690,-4.920,18.196674,1.68,0.583428,2.934498,0.410,0.200,0.625000,0.030,0.320,2.000
...,...,...,...,...,...,...,...,...,...,...,...
734926,-3.540,14.007738,4.65,0.773389,4.063095,1.790,0.940,3.357143,0.120,0.280,4.930
734933,-2.840,13.920575,7.24,0.868929,4.294345,1.995,4.360,9.688889,0.270,0.450,7.690
734940,-3.470,13.516654,4.40,1.807142,4.558411,8.210,1.490,4.806452,0.110,0.310,4.710
734947,-5.840,13.329387,5.68,0.621545,4.609058,2.775,3.760,6.266667,0.230,0.600,6.280
734954,-5.800,13.217534,10.54,-0.280696,4.181677,2.410,10.520,10.313725,0.310,1.020,11.560

In [53]:
print(Orig_block_clean.isna().sum())

N_star                     0
SST                        0
Si_star                    0
U_WIND                     0
WIND_SPD                   0
chlA                       0
nitrate                    0
nitrate_phosphate_ratio    0
nitrite                    0
phosphate                  0
silicate                   0
dtype: int64

In [54]:
block = get_block(Orig_block_clean, num_lags=50, tau=1)

In [55]:
block

,N_star(t-0),SST(t-0),Si_star(t-0),U_WIND(t-0),WIND_SPD(t-0),chlA(t-0),nitrate(t-0),nitrate_phosphate_ratio(t-0),nitrite(t-0),phosphate(t-0),...,SST(t-50),Si_star(t-50),U_WIND(t-50),WIND_SPD(t-50),chlA(t-50),nitrate(t-50),nitrate_phosphate_ratio(t-50),nitrite(t-50),phosphate(t-50),silicate(t-50)
serial_day,,,,,,,,,,,,,,,,,,,,,
725662,-2.200,19.118428,2.06,0.398250,3.219574,0.430,2.520,8.542373,0.020,0.295,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
725669,-2.770,19.229762,2.30,0.701107,3.243543,0.920,2.110,6.918033,0.115,0.305,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
725676,-4.005,19.083670,0.08,0.652186,2.679270,0.615,1.915,5.175676,0.020,0.370,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
725683,-5.125,18.651255,1.17,0.735618,2.754969,0.655,0.155,0.469697,0.020,0.330,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
725690,-4.920,18.196674,1.68,0.583428,2.934498,0.410,0.200,0.625000,0.030,0.320,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
734926,-3.540,14.007738,4.65,0.773389,4.063095,1.790,0.940,3.357143,0.120,0.280,...,14.589881,-0.37,0.422999,3.262202,1.640,0.80,1.951220,0.04,0.41,0.04
734933,-2.840,13.920575,7.24,0.868929,4.294345,1.995,4.360,9.688889,0.270,0.450,...,14.330357,-0.27,-0.254430,4.166964,1.775,0.19,0.678571,0.01,0.28,0.01
734940,-3.470,13.516654,4.40,1.807142,4.558411,8.210,1.490,4.806452,0.110,0.310,...,13.673810,-0.28,-0.054776,4.640476,1.835,0.34,1.133333,0.02,0.30,0.02
734947,-5.840,13.329387,5.68,0.621545,4.609058,2.775,3.760,6.266667,0.230,0.600,...,13.511918,-0.12,1.236447,4.807660,4.520,0.26,2.000000,0.01,0.13,0.01
734954,-5.800,13.217534,10.54,-0.280696,4.181677,2.410,10.520,10.313725,0.310,1.020,...,13.647541,-0.37,1.633663,4.308062,3.905,2.09,4.543478,0.09,0.46,0.09

In [56]:
Orig_block_clean.columns

Index(['N_star', 'SST', 'Si_star', 'U_WIND', 'WIND_SPD', 'chlA', 'nitrate',
       'nitrate_phosphate_ratio', 'nitrite', 'phosphate', 'silicate'],
      dtype='object')

In [59]:
from tqdm import tqdm

E_list = range(2, 13)
tau_list = [-1, -2, -3]
theta_list = [0, 0.1, 0.5, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Tp = 0
exclusion_radius = 0

all_ccm_results = pd.DataFrame()
interactions = list(permutations(Orig_block_clean.columns.tolist(), 2))
print(f'Generated {len(interactions)} total variable interactions.')

target_interactions = [pair for pair in interactions if target in pair]
print(f'Target-involved interactions: {len(target_interactions)}')

results = Parallel(n_jobs=4)(
    delayed(ccm)(interaction, block, E_list, tau_list, theta_list, Tp)
    for interaction in tqdm(target_interactions, desc="Running CCMs")
)

# Make into DataFrame
results_df = pd.DataFrame(results)

Generated 110 total variable interactions.
Target-involved interactions: 20

Running CCMs:  20%|██        | 4/20 [00:00<00:00, 28.70it/s]

('SST', 'chlA')
('U_WIND', 'chlA')
('N_star', 'chlA')
('Si_star', 'chlA')

Running CCMs:  40%|████      | 8/20 [09:50<17:21, 86.76s/it]

('WIND_SPD', 'chlA')
('chlA', 'N_star')
('chlA', 'SST')
('chlA', 'Si_star')

Running CCMs:  60%|██████    | 12/20 [20:52<16:22, 122.79s/it]

('chlA', 'U_WIND')
('chlA', 'WIND_SPD')
('chlA', 'nitrate')
('chlA', 'nitrate_phosphate_ratio')

Running CCMs:  85%|████████▌ | 17/20 [31:43<06:04, 121.47s/it]

('chlA', 'nitrite')
('chlA', 'phosphate')
('chlA', 'silicate')

Running CCMs:  85%|████████▌ | 17/20 [31:58<06:04, 121.47s/it]

('nitrate', 'chlA')

Running CCMs: 100%|██████████| 20/20 [42:32<00:00, 127.63s/it]

('nitrate_phosphate_ratio', 'chlA')

('nitrite', 'chlA')
('phosphate', 'chlA')
('silicate', 'chlA')

In [61]:
results_df

,target (driver),lib (driven),E,tau,theta,E_tau_theta_results,ccm_value,convergence_p_value,correlation
0,N_star,chlA,10,-2,3,E tau theta rho 0 2.0 -1.0...,0.423217,1.827158e-02,0.137084
1,SST,chlA,12,-3,5,E tau theta rho 0 2.0 -1.0...,0.433994,9.703646e-01,-0.121944
2,Si_star,chlA,2,-3,2,E tau theta rho 0 2.0 -1.0...,0.384941,7.280971e-03,0.256457
3,U_WIND,chlA,12,-1,7,E tau theta rho 0 2.0 -1.0...,0.206752,9.993836e-01,0.033607
4,WIND_SPD,chlA,12,-1,5,E tau theta rho 0 2.0 -1.0...,0.237019,9.977293e-01,0.067154
5,chlA,N_star,5,-2,3,E tau theta rho 0 2.0 -1.0...,0.214797,2.065068e-03,0.137084
6,chlA,SST,8,-2,9,E tau theta rho 0 2.0 -1.0...,0.543592,6.293222e-07,-0.121944
7,chlA,Si_star,11,-3,4,E tau theta rho 0 2.0 -1.0...,0.275411,9.790015e-01,0.256457
8,chlA,U_WIND,4,-3,9,E tau theta rho 0 2.0 -1.0...,0.500872,1.968626e-08,0.033607
9,chlA,WIND_SPD,10,-1,8,E tau theta rho 0 2.0 -1.0...,0.461403,4.993821e-09,0.067154
10,chlA,nitrate,2,-2,7,E tau theta rho 0 2.0 -1.0...,0.108284,6.968729e-02,-0.005529
11,chlA,nitrate_phosphate_ratio,12,-3,5,E tau theta rho 0 2.0 -1.0...,0.090766,9.999423e-01,0.025532
12,chlA,nitrite,9,-3,9,E tau theta rho 0 2.0 -1.0...,0.351162,9.113967e-13,-0.066580
13,chlA,phosphate,2,-1,9,E tau theta rho 0 2.0 -1.0...,0.256421,1.566809e-04,-0.106336
14,chlA,silicate,2,-1,1,E tau theta rho 0 2.0 -1.0...,0.265518,9.958751e-01,0.244880
15,nitrate,chlA,12,-1,5,E tau theta rho 0 2.0 -1.0...,0.196728,9.019655e-02,-0.005529
16,nitrate_phosphate_ratio,chlA,12,-1,4,E tau theta rho 0 2.0 -1.0...,0.291587,1.026845e-01,0.025532
17,nitrite,chlA,12,-1,5,E tau theta rho 0 2.0 -1.0...,0.151886,9.999997e-01,-0.066580
18,phosphate,chlA,12,-1,4,E tau theta rho 0 2.0 -1.0...,0.299121,6.718824e-03,-0.106336
19,silicate,chlA,12,-2,2,E tau theta rho 0 2.0 -1.0...,0.367219,1.006703e-01,0.244880

In [62]:
# Get CCM results that show convergence (convergence p-value < 0.05)
results_df = pd.DataFrame(results)
ccm_cutoff = -1

significant_results = results_df[results_df.convergence_p_value<0.20]
significant_results = significant_results.sort_values(by='ccm_value', ascending=False)
significant_results = significant_results[['target (driver)', 'lib (driven)', 'E', 'tau', 'theta', 'ccm_value']].reset_index(drop=True)

display(significant_results[significant_results.ccm_value>ccm_cutoff])

# Choose system variables where the CCM value to or from the target is > ccm_cutoff
system_variables = significant_results[significant_results.ccm_value > ccm_cutoff]
system_variables = system_variables[['target (driver)', 'lib (driven)']].values.flatten().tolist()
system_variables = list(set(system_variables))
print('system variables: ')
display(sorted(system_variables))

            target (driver) lib (driven)   E  tau  theta  ccm_value
0                      chlA          SST   8   -2      9   0.543592
1                      chlA       U_WIND   4   -3      9   0.500872
2                      chlA     WIND_SPD  10   -1      8   0.461403
3                    N_star         chlA  10   -2      3   0.423217
4                   Si_star         chlA   2   -3      2   0.384941
5                  silicate         chlA  12   -2      2   0.367219
6                      chlA      nitrite   9   -3      9   0.351162
7                 phosphate         chlA  12   -1      4   0.299121
8   nitrate_phosphate_ratio         chlA  12   -1      4   0.291587
9                      chlA    phosphate   2   -1      9   0.256421
10                     chlA       N_star   5   -2      3   0.214797
11                  nitrate         chlA  12   -1      5   0.196728
12                     chlA      nitrate   2   -2      7   0.108284

system variables:

['N_star',
 'SST',
 'Si_star',
 'U_WIND',
 'WIND_SPD',
 'chlA',
 'nitrate',
 'nitrate_phosphate_ratio',
 'nitrite',
 'phosphate',
 'silicate']

In [63]:
results_df[results_df.convergence_p_value<0.8].sort_values(by='convergence_p_value', ascending=False)

,target (driver),lib (driven),E,tau,theta,E_tau_theta_results,ccm_value,convergence_p_value,correlation
16,nitrate_phosphate_ratio,chlA,12,-1,4,E tau theta rho 0 2.0 -1.0...,0.291587,1.026845e-01,0.025532
19,silicate,chlA,12,-2,2,E tau theta rho 0 2.0 -1.0...,0.367219,1.006703e-01,0.244880
15,nitrate,chlA,12,-1,5,E tau theta rho 0 2.0 -1.0...,0.196728,9.019655e-02,-0.005529
10,chlA,nitrate,2,-2,7,E tau theta rho 0 2.0 -1.0...,0.108284,6.968729e-02,-0.005529
0,N_star,chlA,10,-2,3,E tau theta rho 0 2.0 -1.0...,0.423217,1.827158e-02,0.137084
2,Si_star,chlA,2,-3,2,E tau theta rho 0 2.0 -1.0...,0.384941,7.280971e-03,0.256457
18,phosphate,chlA,12,-1,4,E tau theta rho 0 2.0 -1.0...,0.299121,6.718824e-03,-0.106336
5,chlA,N_star,5,-2,3,E tau theta rho 0 2.0 -1.0...,0.214797,2.065068e-03,0.137084
13,chlA,phosphate,2,-1,9,E tau theta rho 0 2.0 -1.0...,0.256421,1.566809e-04,-0.106336
6,chlA,SST,8,-2,9,E tau theta rho 0 2.0 -1.0...,0.543592,6.293222e-07,-0.121944
8,chlA,U_WIND,4,-3,9,E tau theta rho 0 2.0 -1.0...,0.500872,1.968626e-08,0.033607
9,chlA,WIND_SPD,10,-1,8,E tau theta rho 0 2.0 -1.0...,0.461403,4.993821e-09,0.067154
12,chlA,nitrite,9,-3,9,E tau theta rho 0 2.0 -1.0...,0.351162,9.113967e-13,-0.066580